# Generated by Django 5.0.4 on 2024-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('flying', 'Flying'), ('normal', 'Normal'), ('ice', 'Ice'), ('psychic', 'Psychic'), ('poisen', 'Poison'), ('fighting', 'Fighting'), ('dragon', 'Dragon'), ('ghost', 'Ghost'), ('dark', 'Dark'), ('ground', 'Ground'), ('fairy', 'Fairy'), ('rock', 'Rock'), ('bug', 'Bug'), ('grass', 'Grass'), ('steel', 'Steel')], max_length=10)),
            ],
        ),
    ]
